import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import "../style/global.css";

const roboto = Roboto({
  subsets: ["latin"], 
  weight: ['400','700']
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className + " bg-solid-grey"}>
        
        <Header /> 
        {children}     
      </body>
    </html>
  );
}
